name: "umbrella"
version: "0.4.0"
usage: "umbrella chart utilities"
description: "utilities for developing umbrella charts"
command: "$HELM_PLUGIN_DIR/bin/umbrella"
hooks:
  install: "cd $HELM_PLUGIN_DIR; scripts/install-plugin.sh"
  update: "cd $HELM_PLUGIN_DIR; scripts/install-plugin.sh"
